version: '3.8'

services:
  customers:
    build: ./service-customers
    ports:
      - 9701:9700
    volumes:
      - ./service-customers:/app
    command: ['tomodachi', 'run', 'src/entrypoints/tomodachi_app.py']
  orders:
    build: ./service-orders
    ports:
      - 9702:9700
    volumes:
      - ./service-orders:/app
    command: ['tomodachi', 'run', 'src/entrypoints/tomodachi_app.py']
  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - 4566:4566
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:4.6.1
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
