version: '3.8'

services:
  app:
    build: .
    ports:
      - 9700:9700
    volumes:
      - .:/app
    command: ['tomodachi', 'run', 'src/entrypoints/tomodachi_app.py']
    environment:
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SNS_TOPIC_PREFIX=d6013159
      - AWS_SQS_QUEUE_NAME_PREFIX=d6013159
      - DYNAMODB_TABLE_NAME=tomodachi-transactional-outbox
